===============================================
当切换为中文语言，进入`管理员界面`时候，提示出错。
提示如下错误：
---------------------------
/home/user/project/nodeshot/env/local/lib/python2.7/site-packages/grappelli/dashboard/utils.py in <lambda>
 113                       pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8'))) 

Local vars
Variable	Value
x	
(<class 'nodeshot.community.profiles.models.emailconfirmation.EmailConfirmation'>,
 {'add': True, 'change': True, 'delete': True})
---------------------------
/home/user/project/nodeshot/env/local/lib/python2.7/site-packages/django/utils/functional.py in __wrapper__
136                            return getattr(res, method_name)(*args, **kw) 

Local vars
Variable	Value
res '\xe9\x82\xae\xe4\xbb\xb6\xe7\xa1\xae\xe8\xae\xa4'
self	<django.utils.functional.__proxy__ object at 0x7f3d6f6283d0>
args	(u'utf-8',)
method_name	'encode'
kw	{}
func	<function gettext at 0x7f3d88363050>
---------------------------
上述错误，实际上是因为`grappelli`模块里面，解析模板的`Meta`的`verbose_name_plural`,尝试使用`utf-8`编码时，导致的错误。
===============================================



===============================================
原因是，我们翻译了一个字段：`重设密码`。

我们搜索一下关键字：`重设密码`，结果如下：
------------------------
(env) user@osgeolive:~/project/nodeshot/nodeshot$ grep -rainI "重设密码" . -C3
./doc/chinese/ugettext_error.txt-1-当切换为中文语言，进入管理员界面时候，提示出错。
./doc/chinese/ugettext_error.txt:2:原因是，我们翻译了一个字段：`重设密码`。
./doc/chinese/ugettext_error.txt-3-
./doc/chinese/ugettext_error.txt-4-我们发现最终是在文件`password_reset.py`：
./doc/chinese/ugettext_error.txt-5-
--
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-109-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-110-#: models/password_reset.py:57
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-111-msgid "password reset"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:112:msgstr "重设密码"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-113-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-114-#: models/password_reset.py:58
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-115-msgid "password resets"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:116:msgstr "重设密码"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-117-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-118-#: models/profile.py:17
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-119-msgid "male"
------------------------

我们发现是在文件`password_reset.py`：57,进行了翻译：
------------------------
    class Meta:
        verbose_name = _('password reset')
        verbose_name_plural = _('password resets')
        app_label = 'profiles'
------------------------
===============================================

===============================================
------------------------
https://github.com/sehmaschine/django-grappelli/commit/82fcaddca2730bc36206ad30806d06edcb2fb290
------------------------

有个人，在网上报了类似的问题：
------------------------
https://github.com/sehmaschine/django-grappelli/issues/620
------------------------
有个人，出现了和我类似的问题，它以为`bug#590`,仍然没有解决，实际上是`他`自己的错误。
使用方法不对，应该使用unicode对象，如下所示：
------------------------------
Edit: I found #590, it seems to be the same problem, still not resolved.

#590：https://github.com/sehmaschine/django-grappelli/issues/590

 @m-aciek
m-aciek commented on Jun 1, 2015
My fault, marking strings as unicode did the work.

class Meta:
        verbose_name = u"zamówienie"
        verbose_name_plural = u"zamówienia"
------------------------------
是的，必须给`字符串`，使用`unicode`形式。

===============================================
bug#590
------------------------
https://github.com/sehmaschine/django-grappelli/issues/590
------------------------

-----------------------------
alright ... I finally could reproduce this. using "unicode" doesn't make sense since python3 uses "str".

my suggestion is to change line 113 of `utils.py` to:
pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))

maybe someone can test this as well and give some feedback. from my point of view, it's a clean solution and it should work with python2 and python3.
-----------------------------

`grappelli1`的作者，修改代码为：
-----------------------------
https://github.com/sehmaschine/django-grappelli/commit/82fcaddca2730bc36206ad30806d06edcb2fb290
-            pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural))
+            pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))
-----------------------------
===============================================

===============================================
我们出错，应该是没有使用`unicode`导致的结果。
这里我们发现在代码`password_reset.py`文件的头部：
------------------------
from django.utils.translation import ugettext_lazy as _
------------------------
通常我们的`项目`的`头部`应该是如下：
------------------------
from django.utils.translation import ugettext_lazy as _
------------------------
所以将其修改，进行尝试。
===============================================

===============================================
使用命令：
------------------------
grep -rainIw "ugettext_lazy" .
或者
rg -w  "ugettext_lazy" 
------------------------
你会发现有许多这种用法。

但是，作者也有打盹的时候，你会发现，有些地方，仍然使用了`gettext_lazy`,而不是`ugettext_lazy`.

查找`gettext_lazy`在哪些地方出现：
使用如下命令：
------------------------
rg -w  "gettext_lazy"
或者
grep -rainIw "gettext_lazy" .
------------------------
执行结果如下：
------------------------
(env) user@osgeolive:~/project/nodeshot/nodeshot$ grep -rainIw "gettext_lazy" .
./dev/dev/settings.py:3:from django.utils.translation import gettext_lazy as _
./nodeshot/community/profiles/models/emailconfirmation.py:10:from django.utils.translation import gettext_lazy as _
./nodeshot/community/profiles/models/password_reset.py:2:from django.utils.translation import gettext_lazy as _
------------------------
===============================================

但是仍然不起作用。

实际上，我们修改如下内容:
----------------------------
    class Meta:
        # verbose_name = _('password reset')
        verbose_name = u'HELLO'
        verbose_name_plural = _('password resets')
        app_label = 'profiles'
----------------------------
我们使用`verbose_name`


接着，应为`邮件确认`，仍然报错。
------------------------------
user@osgeolive:~/project/nodeshot/nodeshot$ grep -rainIw "邮件确认" .
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:84:msgstr "邮件确认"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:88:msgstr "邮件确认"
------------------------------
为了更详细查看，运行命令：
------------------------------
user@osgeolive:~/project/nodeshot/nodeshot$ grep -rainIw "邮件确认" . -C3
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-81-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-82-#: models/emailconfirmation.py:209
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-83-msgid "email confirmation"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:84:msgstr "邮件确认"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-85-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-86-#: models/emailconfirmation.py:210
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-87-msgid "email confirmations"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po:88:msgstr "邮件确认"
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-89-
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-90-#: models/password_reset.py:31
./nodeshot/community/profiles/locale/zh_CN/LC_MESSAGES/django.po-91-msgid "Password reset email sent"
------------------------------
我们可以确认，是文件`models/emailconfirmation.py`文件，209行，210行，
当对其进行翻译时，引发的问题。
------------------------
    class Meta:
        app_label = 'profiles'
        verbose_name = _("email confirmation")
        verbose_name_plural = _("email confirmations")
------------------------------
所以，按照之前处理`重设密码`的方式，做相同的处理。
在文件`models/emailconfirmation.py`文件，
------------------------------
from django.utils.translation import gettext_lazy as _
------------------------------
改为：
------------------------------
from django.utils.translation import ugettext_lazy as _
------------------------------

结果，这两个翻译的问题，导致无法进入`管理界面`的情况，得到解决。


